---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

-  Homelab EntryPoints:
    - Gitlab:
        href: https://gitlabf.lurking.site
        description: Local Gitlab instance
        icon: gitlab.png
        ping: localhost

    - Traefik:
        widget:
        type: traefik
        url: http://localhost:8080
        

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎



