---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS:?HOMEPAGE_ALLOWED_HOSTS not set}
      - LOG_LEVEL=info
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage-http.rule=Host(`homepage.local`)
      - traefik.http.routers.homepage-http.entrypoints=web
      - traefik.http.routers.homepage-https.tls=true
      - traefik.http.routers.homepage-https.tls.certresolver=cloudflare
      - traefik.http.routers.homepage-https.entrypoints=websecure
      - traefik.http.routers.homepage-https.rule=Host(`homepage.lurking.site`)
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/images  # for custom background images
      - ./icons:/app/icons  # for custom icons
    restart: unless-stopped
networks:
  frontend:
    external: true