services:
  loki:
    container_name: loki
    image: docker.io/grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml"
    volumes:
      - ./config/config.yaml:/etc/loki/config.yaml:ro
      - data_loki:/loki:rw
    labels:
      - "traefik.enable=true"
      # -- Traefik Service
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.services.loki.loadbalancer.server.scheme=http"
      # -- Traefik Router
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.rule=Host(`loki.lurking.site`)"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.routers.loki.tls.certresolver=cloudflare"
    networks:
      - frontend
    restart: unless-stopped

volumes:
  data_loki:
    driver: local

networks:
  frontend:
    external: true
