name: docker-cache
services:
    registry:
        restart: always
        container_name: docker-cache
        ports:
            - 5000:5000
        volumes:
            - /opt/docker-cache:/var/lib/registry
        environment:
            - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
        image: registry:2